### ISSUE TITLE
Schema version quoting issue?

### ISSUE THREAD

**Issue by rchekaluk** [skryl/qbxml#13]
This error from qbxml looks fishy:
```
invalid version '7.0' for schema qb, must be one of [\"2.0\", \"CA3.0\", \"3.0\", \"4.0\", \"4.1\", \"5.0\", \"6.0\", \"7.0\", \"8.0\", \"10.0\", \"11.0\", \"12.0\", \"13.0\"]
```

**Comment by JasonBarnabe** [comment]
Are you specifying a number or a string?

**Comment by rchekaluk** [comment]
This assignment from config/initializers/qbwc.rb is apparently sending a Float into qbxml:
```ruby
c.min_version = 7.0
```
Changing it to a string works around and prevents this error, though it still seems that qbxml should be able to handle a Float.

**Comment by JasonBarnabe** [comment]
Yeah, I agree.
